import streamlit as st
import pickle
import pandas as pd
import numpy as np
import shap
import datetime
import plotly.graph_objects as go
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
import plotly.express as px

# ========== CONFIG ==========
st.set_page_config(
    page_title="Infidelity Risk Predictor",
    page_icon="💔",
    layout="wide"
)

# ========== LOAD MODEL ==========
@st.cache_resource
def load_model():
    with open('model/xgb_model.pkl', 'rb') as f:
        model_data = pickle.load(f)
    return model_data['model'], model_data['feature_names']

model, feature_names = load_model()

# ========== MAPPING ==========
ordinal_mappings = {
    'kepuasan_hubungan': {'Rendah': 0, 'Sedang': 1, 'Tinggi': 2},
    'kualitas_komunikasi': {'Rendah': 0, 'Sedang': 1, 'Tinggi': 2},
    'keintiman_emosional': {'Rendah': 0, 'Sedang': 1, 'Tinggi': 2},
    'empati_pasangan': {'Rendah': 0, 'Tinggi': 1},
    'merasa_diperhatikan': {'Tidak': 0, 'Iya': 1},
    'konflik_berulang': {'Jarang': 0, 'Sering': 1},
    'impulsif': {'Tidak': 0, 'Iya': 1},
    'komunikasi_rahasia': {'Tidak': 0, 'Iya': 1},
    'lingkungan_kerja_intens': {'Tidak': 0, 'Iya': 1},
    'masih_kontak_mantan': {'Tidak': 0, 'Iya': 1},
    'hubungan_jarak_jauh': {'Tidak': 0, 'Iya': 1},
    'curhat_ke_orang_lain': {'Tidak': 0, 'Iya': 1},
    'merasa_lebih_dimengerti_orang_lain': {'Tidak': 0, 'Iya': 1},
    'menyembunyikan_interaksi': {'Tidak': 0, 'Iya': 1},
    'berbagi_masalah_pribadi_ke_luar': {'Tidak': 0, 'Iya': 1},
    'punya_anak': {'Tidak': 0, 'Iya': 1},
    'masalah_ekonomi': {'Tidak': 0, 'Iya': 1},
    'konflik_besar_terakhir': {'Tidak': 0, 'Iya': 1},
    'konsumsi_alkohol': {'Tidak': 0, 'Iya': 1},
    'intensitas_dm_lawan_jenis': {'Rendah': 0, 'Sedang': 1, 'Tinggi': 2},
    'kebutuhan_validasi': {'Rendah': 0, 'Sedang': 1, 'Tinggi': 2},
    'kontrol_diri': {'Rendah': 0, 'Tinggi': 1},
    'stres_pekerjaan': {'Rendah': 0, 'Tinggi': 1},
    'gaya_kelekatan': {'Aman': 0, 'Cemas': 1, 'Menghindar': 2},
    'pandangan_tentang_selingkuh': {'Salah Total': 0, 'Manusiawi': 1},
    'religiusitas_pribadi': {'Rendah': 0, 'Tinggi': 1},
    'toleransi_selingkuh': {'Nol': 0, 'Rendah': 1, 'Tinggi': 2},
    'nilai_kesetiaan': {'Lemah': 0, 'Kuat': 1},
    'status_hubungan': {'Pacaran': 0, 'Menikah': 1},
    'rencana_masa_depan_bersama': {'Tidak Jelas': 0, 'Jelas': 1},
    'ketergantungan_emosional': {'Rendah': 0, 'Tinggi': 1},
    'jenis_kelamin': {'Wanita': 0, 'Pria': 1},
    'pendidikan_terakhir': {'SMA': 0, 'D3': 1, 'S1': 2, 'S2': 3},
    'status_pekerjaan': {'Freelance': 0, 'Wirausaha': 1, 'Karyawan': 2},
    'domisili': {'Rural': 0, 'Suburban': 1, 'Urban': 2}
}

label_map = {0: 'Aman & Sehat', 1: 'Perlu Perhatian', 2: 'Waspada Tinggi'}

# ========== HEADER ==========
st.title("💔 Infidelity Risk: Early Warning System")
st.markdown("**AI** untuk deteksi risiko selengki **sebelum kejadian**, bukan nuduh tapi early warning. **Dataset**: 8 CSV files dengan 3000 responden (Dummy generated by ChatGPT). Model yang digunakan adalah **XGBoost**. Evaluasi menggunakan **SHAP** untuk mengetahui faktor-faktor yang mempengaruhi prediksi.")
st.markdown("---")

# ========== INPUT FORM ==========
st.subheader("📝 Isi Data Kamu")

col1, col2, col3 = st.columns(3)

with col1:
    st.caption("1. **Kepuasan Hubungan**")
    kepuasan = st.radio("Kepuasan Hubungan", list(ordinal_mappings['kepuasan_hubungan'].keys()), horizontal=True)
    komunikasi = st.radio("Kualitas Komunikasi", list(ordinal_mappings['kualitas_komunikasi'].keys()), horizontal=True)
    diperhatikan = st.radio("Merasa Diperhatikan", list(ordinal_mappings['merasa_diperhatikan'].keys()), horizontal=True)
    keintiman = st.radio("Keintiman Emosional", list(ordinal_mappings['keintiman_emosional'].keys()), horizontal=True)
    konflik = st.radio("Konflik Berulang", list(ordinal_mappings['konflik_berulang'].keys()), horizontal=True)

    st.caption("2. **Akses & Kesempatan**")
    dm_lawan = st.radio("Intensitas DM Lawan Jenis", list(ordinal_mappings['intensitas_dm_lawan_jenis'].keys()), horizontal=True)
    komun_rahasia = st.radio("Komunikasi Rahasia", list(ordinal_mappings['komunikasi_rahasia'].keys()), horizontal=True)
    kerja_intens = st.radio("Lingkungan Kerja Intens", list(ordinal_mappings['lingkungan_kerja_intens'].keys()), horizontal=True)
    kontak_mantan = st.radio("Masih Kontak Mantan", list(ordinal_mappings['masih_kontak_mantan'].keys()), horizontal=True)
    jarak_jauh = st.radio("Hubungan Jarak Jauh", list(ordinal_mappings['hubungan_jarak_jauh'].keys()), horizontal=True)

    st.caption("3. **Nilai & Sikap**")
    pandangan = st.radio("Pandangan tentang Selingkuh", list(ordinal_mappings['pandangan_tentang_selingkuh'].keys()), horizontal=True)
    religius = st.radio("Religiusitas Pribadi", list(ordinal_mappings['religiusitas_pribadi'].keys()), horizontal=True)

with col2:
    toleransi = st.radio("Toleransi Selingkuh", list(ordinal_mappings['toleransi_selingkuh'].keys()), horizontal=True)
    kesetiaan = st.radio("Nilai Kesetiaan", list(ordinal_mappings['nilai_kesetiaan'].keys()), horizontal=True)

    st.caption("4. **Profil Psikologis**")
    gaya_kel = st.radio("Gaya Kelekatan", list(ordinal_mappings['gaya_kelekatan'].keys()), horizontal=True)
    validasi = st.radio("Kebutuhan Validasi", list(ordinal_mappings['kebutuhan_validasi'].keys()), horizontal=True)
    kontrol = st.radio("Kontrol Diri", list(ordinal_mappings['kontrol_diri'].keys()), horizontal=True)
    impulsif = st.radio("Impulsif", list(ordinal_mappings['impulsif'].keys()), horizontal=True)
    empati = st.radio("Empati Pasangan", list(ordinal_mappings['empati_pasangan'].keys()), horizontal=True)

    st.caption("5. **Kedekatan Emosional Lain**")
    curhat = st.radio("Curhat ke Orang Lain", list(ordinal_mappings['curhat_ke_orang_lain'].keys()), horizontal=True)
    dimengerti_lain = st.radio("Merasa Lebih Dimengerti Orang Lain", list(ordinal_mappings['merasa_lebih_dimengerti_orang_lain'].keys()), horizontal=True)
    sembunyikan = st.radio("Menyembunyikan Interaksi", list(ordinal_mappings['menyembunyikan_interaksi'].keys()), horizontal=True)
    berbagi_masalah = st.radio("Berbagi Masalah Pribadi ke Luar", list(ordinal_mappings['berbagi_masalah_pribadi_ke_luar'].keys()), horizontal=True)

    st.caption("6. **Komitmen Hubungan**")
    status_hub = st.radio("Status Hubungan", list(ordinal_mappings['status_hubungan'].keys()), horizontal=True)

with col3:
    lama_hub = st.number_input("Lama Hubungan (tahun)", min_value=0, max_value=50, value=3)
    punya_anak = st.radio("Punya Anak", list(ordinal_mappings['punya_anak'].keys()), horizontal=True)
    rencana = st.radio("Rencana Masa Depan Bersama", list(ordinal_mappings['rencana_masa_depan_bersama'].keys()), horizontal=True)
    ketergantungan = st.radio("Ketergantungan Emosional", list(ordinal_mappings['ketergantungan_emosional'].keys()), horizontal=True)

    st.caption("7. **Pemicu Stres**")
    stres_kerja = st.radio("Stres Pekerjaan", list(ordinal_mappings['stres_pekerjaan'].keys()), horizontal=True)
    ekonomi = st.radio("Masalah Ekonomi", list(ordinal_mappings['masalah_ekonomi'].keys()), horizontal=True)
    konflik_besar = st.radio("Konflik Besar Terakhir", list(ordinal_mappings['konflik_besar_terakhir'].keys()), horizontal=True)
    alkohol = st.radio("Konsumsi Alkohol", list(ordinal_mappings['konsumsi_alkohol'].keys()), horizontal=True)

    st.caption("8. **Demografi**")
    usia = st.number_input("Usia", min_value=18, max_value=80, value=25)
    jenis_kelamin = st.radio("Jenis Kelamin", list(ordinal_mappings['jenis_kelamin'].keys()), horizontal=True)
    pendidikan = st.radio("Pendidikan Terakhir", list(ordinal_mappings['pendidikan_terakhir'].keys()), horizontal=True)
    pekerjaan = st.radio("Status Pekerjaan", list(ordinal_mappings['status_pekerjaan'].keys()), horizontal=True)
    domisili = st.radio("Domisili", list(ordinal_mappings['domisili'].keys()), horizontal=True)

# ========== PREDICTION ==========
if st.button("🔍 Analisis Risiko", type="secondary", use_container_width=True):
    # Prepare input
    user_input = {
        'kepuasan_hubungan': ordinal_mappings['kepuasan_hubungan'][kepuasan],
        'kualitas_komunikasi': ordinal_mappings['kualitas_komunikasi'][komunikasi],
        'merasa_diperhatikan': ordinal_mappings['merasa_diperhatikan'][diperhatikan],
        'keintiman_emosional': ordinal_mappings['keintiman_emosional'][keintiman],
        'konflik_berulang': ordinal_mappings['konflik_berulang'][konflik],
        'gaya_kelekatan': ordinal_mappings['gaya_kelekatan'][gaya_kel],
        'kebutuhan_validasi': ordinal_mappings['kebutuhan_validasi'][validasi],
        'kontrol_diri': ordinal_mappings['kontrol_diri'][kontrol],
        'impulsif': ordinal_mappings['impulsif'][impulsif],
        'empati_pasangan': ordinal_mappings['empati_pasangan'][empati],
        'intensitas_dm_lawan_jenis': ordinal_mappings['intensitas_dm_lawan_jenis'][dm_lawan],
        'komunikasi_rahasia': ordinal_mappings['komunikasi_rahasia'][komun_rahasia],
        'lingkungan_kerja_intens': ordinal_mappings['lingkungan_kerja_intens'][kerja_intens],
        'masih_kontak_mantan': ordinal_mappings['masih_kontak_mantan'][kontak_mantan],
        'hubungan_jarak_jauh': ordinal_mappings['hubungan_jarak_jauh'][jarak_jauh],
        'curhat_ke_orang_lain': ordinal_mappings['curhat_ke_orang_lain'][curhat],
        'merasa_lebih_dimengerti_orang_lain': ordinal_mappings['merasa_lebih_dimengerti_orang_lain'][dimengerti_lain],
        'menyembunyikan_interaksi': ordinal_mappings['menyembunyikan_interaksi'][sembunyikan],
        'berbagi_masalah_pribadi_ke_luar': ordinal_mappings['berbagi_masalah_pribadi_ke_luar'][berbagi_masalah],
        'pandangan_tentang_selingkuh': ordinal_mappings['pandangan_tentang_selingkuh'][pandangan],
        'religiusitas_pribadi': ordinal_mappings['religiusitas_pribadi'][religius],
        'toleransi_selingkuh': ordinal_mappings['toleransi_selingkuh'][toleransi],
        'nilai_kesetiaan': ordinal_mappings['nilai_kesetiaan'][kesetiaan],
        'status_hubungan': ordinal_mappings['status_hubungan'][status_hub],
        'lama_hubungan_tahun': lama_hub,
        'punya_anak': ordinal_mappings['punya_anak'][punya_anak],
        'rencana_masa_depan_bersama': ordinal_mappings['rencana_masa_depan_bersama'][rencana],
        'ketergantungan_emosional': ordinal_mappings['ketergantungan_emosional'][ketergantungan],
        'stres_pekerjaan': ordinal_mappings['stres_pekerjaan'][stres_kerja],
        'masalah_ekonomi': ordinal_mappings['masalah_ekonomi'][ekonomi],
        'konflik_besar_terakhir': ordinal_mappings['konflik_besar_terakhir'][konflik_besar],
        'konsumsi_alkohol': ordinal_mappings['konsumsi_alkohol'][alkohol],
        'usia': usia,
        'jenis_kelamin': ordinal_mappings['jenis_kelamin'][jenis_kelamin],
        'pendidikan_terakhir': ordinal_mappings['pendidikan_terakhir'][pendidikan],
        'status_pekerjaan': ordinal_mappings['status_pekerjaan'][pekerjaan],
        'domisili': ordinal_mappings['domisili'][domisili]
    }
    
    input_df = pd.DataFrame([user_input])
    
    # Predict
    prediction = model.predict(input_df)[0]
    proba = model.predict_proba(input_df)[0]
    confidence = int(proba[prediction] * 100)
    
    # ========== RESULTS & RISK FACTORS ========== 
    st.markdown("---")
    st.subheader("📊 Hasil Prediksi Risiko")

    # Prepare SHAP analysis first
    explainer = shap.TreeExplainer(model)
    shap_values = explainer.shap_values(input_df)

    # Focus on high risk class (class 2)
    if isinstance(shap_values, list) and len(shap_values) >= 3:
        shap_for_class2 = shap_values[2][0]
    elif isinstance(shap_values, np.ndarray) and shap_values.ndim == 3:
        shap_for_class2 = shap_values[0, :, 2]
    else:
        if hasattr(shap_values, 'shape') and len(shap_values.shape) > 1:
            shap_for_class2 = shap_values[0]
        else:
            shap_for_class2 = shap_values

    shap_for_class2 = np.array(shap_for_class2).flatten()

    # Create feature importance dataframe
    feature_importance = pd.DataFrame({
        'feature': input_df.columns.tolist(),
        'shap_value': shap_for_class2.tolist(),
        'abs_impact': np.abs(shap_for_class2).tolist(),
        'nilai_anda': input_df.values[0].tolist()
    })

    # Get top factors
    top_positive = feature_importance[feature_importance['shap_value'] > 0].nlargest(3, 'abs_impact').sort_values('abs_impact', ascending=True)
    top_negative = feature_importance[feature_importance['shap_value'] < 0].nlargest(3, 'abs_impact').sort_values('abs_impact', ascending=True)

    # Display all results in one row
    result_col1, result_col2, result_col3, result_col4 = st.columns([1, 1, 1, 1])

    with result_col1:
        if prediction == 0:
            st.markdown("<small>Status Saat Ini:</small>", unsafe_allow_html=True)
            st.success(f"### ✅ {label_map[prediction]}")
        elif prediction == 1:
            st.markdown("<small>Status Saat Ini:</small>", unsafe_allow_html=True)
            st.warning(f"### ⚠️ {label_map[prediction]}")
        else:
            st.markdown("<small>Status Saat Ini:</small>", unsafe_allow_html=True)
            st.error(f"### 🚨 {label_map[prediction]}")
        st.metric("Tingkat Keyakinan AI:", f"{confidence}%")

    with result_col2:
        st.markdown("**Distribusi Probabilitas**")

        labels = ['Aman & Sehat', 'Perlu Perhatian', 'Waspada Tinggi']
        proba_percent = [p * 100 for p in proba]
        proba_df = pd.DataFrame({
            'Kategori': labels,
            'Probabilitas': proba_percent
        })
        fig_bar = px.bar(
            proba_df,
            x='Probabilitas',
            y='Kategori',
            text='Probabilitas',
            orientation='h',
            color='Kategori',
            color_discrete_sequence=["#27ae60", "#f1c40f", "#e74c3c"]
        )
        fig_bar.update_traces(texttemplate='%{text:.0f}%', textposition='outside')
        fig_bar.update_layout(
            yaxis=dict(title=''),
            xaxis=dict(title='Probabilitas (%)', range=[0, 100]),
            showlegend=False,
            margin=dict(t=10, b=10, l=0, r=0),
            height=200
        )
        st.plotly_chart(fig_bar, use_container_width=True)

    with result_col3:
        st.markdown("**⚠️ Top 3 Faktor Meningkatkan Risiko**")
        if not top_positive.empty:
            total_shap = top_positive['abs_impact'].sum()
            percent_list = [(row['abs_impact'] / total_shap * 100) if total_shap > 0 else 0 for _, row in top_positive.iterrows()]
            label_list = [
                f"{row['feature'].replace('_', ' ').title()}: {list(ordinal_mappings[row['feature']].keys())[list(ordinal_mappings[row['feature']].values()).index(int(row['nilai_anda']))] if row['feature'] in ordinal_mappings else row['nilai_anda']}"
                for _, row in top_positive.iterrows()
            ]
            
            pos_fig = go.Figure(go.Bar(
                x=percent_list,
                y=label_list,
                orientation='h',
                text=[f"{p:.1f}%" for p in percent_list],
                textposition='outside',
                marker_color='#e74c3c',
            ))
            pos_fig.update_layout(
                xaxis_title='Kontribusi (%)',
                yaxis_title='',
                margin=dict(l=0, r=0, t=10, b=10),
                height=220,
                xaxis_range=[0, 100]
            )
            st.plotly_chart(pos_fig, use_container_width=True)
        else:
            st.info("Tidak ada faktor dominan")

    with result_col4:
        st.markdown("**✅ Top 3 Faktor Menurunkan Risiko**")
        if not top_negative.empty:
            total_shap = top_negative['abs_impact'].sum()
            percent_list = [(row['abs_impact'] / total_shap * 100) if total_shap > 0 else 0 for _, row in top_negative.iterrows()]
            label_list = [
                f"{row['feature'].replace('_', ' ').title()}: {list(ordinal_mappings[row['feature']].keys())[list(ordinal_mappings[row['feature']].values()).index(int(row['nilai_anda']))] if row['feature'] in ordinal_mappings else row['nilai_anda']}"
                for _, row in top_negative.iterrows()
            ]

            neg_fig = go.Figure(go.Bar(
                x=percent_list,
                y=label_list,
                orientation='h',
                text=[f"{p:.1f}%" for p in percent_list],
                textposition='outside',
                marker_color='#27ae60',
            ))
            neg_fig.update_layout(
                xaxis_title='Kontribusi (%)',
                yaxis_title='',
                margin=dict(l=0, r=0, t=10, b=10),
                height=220,
                xaxis_range=[0, 100]
            )
            st.plotly_chart(neg_fig, use_container_width=True)
        else:
            st.info("Tidak ada faktor dominan")

    st.info("💡 **Catatan**: Hasil ini adalah prediksi berbasis AI dan  sebaiknya tidak dijadikan satu-satunya acuan tanpa konsultasi dengan profesional.")

# ========== FOOTER ==========
st.markdown("---")
st.caption(f"Copyright © {datetime.datetime.now().year} "
           f"[Damelia](https://www.youtube.com/@CERDASBersamaDamelia). All Rights Reserved.")